version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-bank
    container_name: laravel-bank-backend
    ports:
      - '8001:80'
    env_file: .env
